---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Welcome
- type: document
  path: README.md
  label: Home
- type: document
  path: mission/README.md
  label: Mission
- type: document
  path: background/README.md
  label: Background
- type: document
  path: year-5/README.md
  label: Year 5
  match: "**/*"
- type: directory
  path: ''
  label: Browse
  create: all
  match: "**/*"
upload_dir: public/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: vuepress build -d .vuepress/dist
  publish_command: vuepress build -d .vuepress/dist
  preview_output_directory: ".vuepress/dist"
  output_directory: ".vuepress/dist"
  instant_preview_command: vuepress dev -p 8080 -h 0.0.0.0
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
